runtime: php72
api_version: 1
automatic_scaling:
  max_idle_instances: 1
handlers:
- url: /bootstrap
  static_dir: web/bootstrap
- url: /css
  static_dir: web/css
- url: /fonts
  static_dir: web/fonts
- url: /images
  static_dir: web/images
- url: /js
  static_dir: web/js
- url: /.*
  script: web/index.php
