name: CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: php-actions/composer@v5 # or alternative dependency management
            - name: run tests
              run: composer test
            - name: change owner of phpcs
              run: sudo chmod 777 ./vendor/bin/phpcs
            - name: sniff
              run: composer sniff
